[package]
name = "perlmod-test"
version = "0.1.0"
authors = ["Wolfgang Bumiller <w.bumiller@proxmox.com>"]
edition = "2018"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
anyhow = "1.0"
perlmod = { path = "../perlmod", features = [ "exporter" ] }
