[package]
name = "perlmod-macro"
version = "0.1.0"
authors = ["Wolfgang Bumiller <w.bumiller@proxmox.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
categories = [ "API bindings" ]
keywords = [ "ffi", "perl" ]

[badges]
maintenance = { status = "experimental" }

[lib]
proc-macro = true

[dependencies]
failure = "0.1"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = [ "full" ] }
toml = "0.5.5"

[dev-dependencies]
perlmod = { path = "../perlmod" }
