[workspace]
members = [
    "perlmod",
    "perlmod-macro",
    "perlmod-test",
]
exclude = [
    "build",
]

[workspace.package]
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2021"
license = "Apache-2.0 OR MIT"
repository = "https://git.proxmox.com/?p=perlmod.git"
